description: "#{repo}"
builds:
- platform: "linux"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_nodejs-12.22.1_generic_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian' || entity.system.platform_family == 'rhel'"
- platform: "alpine"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_nodejs-12.22.1_alpine_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'alpine'"
  -  "entity.system.platform_version.split('.')[0] == '3'"
  -  "parseInt(entity.system.platform_version.split('.')[1]) >= 9"